name: RpcView Build

on: [push]

jobs:
  RpcView-x86:

    runs-on: windows-2016

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python3.7 version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.9.1
          host: windows
          target: desktop
          arch: win32_msvc2017
      - name: Build RpcView-x86
        env:
          CMAKE_PREFIX_PATH: ${{ runner.workspace }}\Qt\5.9.1\msvc2017
        run: |
          mkdir Build\x86
          cd Build\x86
          cmake ..\.. -G"Visual Studio 15 2017"
          cmake --build . --config Release
          ${{ runner.workspace }}\Qt\5.9.1\msvc2017\bin\windeployqt.exe .\bin\Release\RpcView.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: RpcView-x86.zip
          path: ${{ runner.workspace }}\RpcView\Build\x86\bin\Release

  RpcView-x64:

    runs-on: windows-2016

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python3.7 version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.9.1
          host: windows
          target: desktop
          arch: win64_msvc2017_64
      - name: Build RpcView-x64
        env:
          CMAKE_PREFIX_PATH: ${{ runner.workspace }}\Qt\5.9.1\msvc2017_64
        run: |
          mkdir Build\x64
          cd Build\x64
          cmake ..\.. -G"Visual Studio 15 2017 Win64"
          cmake --build . --config Release
          ${{ runner.workspace }}\Qt\5.9.1\msvc2017_64\bin\windeployqt.exe .\bin\Release\RpcView.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: RpcView-x64.zip
          path: ${{ runner.workspace }}\RpcView\Build\x64\bin\Release
